apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: api-port
      port: 5000
      targetPort: 5000
      nodePort: 30001